Add docker
LachlanCourt/rainbowBot pull request #141
Opened 2023-01-28 11:08 UTC by LachlanCourt

2023-01-28 11:13 UTC, LachlanCourt commented
I'll be removing the build and push test for PRs but I have it here to test and bugfix before merging into main

2023-01-31 12:00 UTC, Y0sh1dk requested changes

2023-01-31 12:00 UTC, Y0sh1dk commented on .github/workflows/build-and-push-main.yml
> +    - name: Login to GitHub Container Registry
Logging into the container registry should be the first step in the pipeline, uncase the login fails we dont waste any time building the image unnecessarily

2023-01-31 12:00 UTC, Y0sh1dk commented on Dockerfile
> +FROM python:3.12-rc-alpine as base
```suggestion
ARG PYTHON_VERSION=3.12

FROM python:${PYTHON_VERSION}-rc-alpine as base
```

Due to the python version being referenced in multiple places at build time, it should be an `ARG`. `${PYTHON_VERSION}` can also be used further down

2023-01-31 12:00 UTC, Y0sh1dk commented on Makefile
> +build:
This Makefile should also accept env vars so it can be used in the pipeline

2023-01-31 12:18 UTC, LachlanCourt commented on Makefile
> +push:
Because I needed a generic tag? 😅
Mostly borrowed from NUbots - is there a better one semantically?

2023-02-04 05:13 UTC, Y0sh1dk submitted a review, later dismissed
LGTM

2023-02-04 05:18 UTC, Y0sh1dk submitted a review, later dismissed

2023-02-04 05:20 UTC, merged